[vote]
output = """
List Link
- &b&lhttps://www.google.com&r
- &c&lhttps://ur-mom.com&r
- &0&lhttps://nig.ga&r
- &f&lhttps://twitch.tv&r
- &b&l&nhttps://vote.lorest.one&r
- &9Me &r{and} &dYou
Also, a little reminder
ur vote is just %lorevote_player_amount%, vote more lah
"""

[vote.broadcast]
message = "Helo fren, im under de water, yor vote karenli is %lorevote_player_amount%"
interval = 200 # as in ticks, https://mapmaking.fr/tick/

[vote.player]
rewards = [
    "give {username} wooden_sword",
    "give {username} dirt"
]

[vote.party]
goal = 22
rewards = [
    "give @a wooden_sword",
    "give @a dirt"
]

[vote.party.chance_rewards]
5 = ["give {username} netherite_hoe", "give {username} stick 64"]
10 = ["give {username} wooden_sword", "give {username} wooden_hoe"]
90 = ["give {username} dirt"]

[broadcast]
message = "&c&l{username}&r just voted using &a&l{service} &r{and} their vote is now %lorevote_player_amount%"
